### ISSUE TITLE
Tracks command picks the song instead of the album if they have the same name

### ISSUE THREAD

**Issue by daves003** [ishwi/Chuu#44]
When using the `tracks` command, Chuu will display only the Titletrack instead of the whole album if they have the same name.
For example the album "Lifeblood" by the band "Brand of Sacrifice" has a track titled "Lifeblood" on it which causes it to only display that track.

![Screenshot_20210309_113120](https://user-images.githubusercontent.com/73641169/110458134-b054dc80-80cb-11eb-900c-b55d080f8132.png)

**Comment by ishwi** [comment]
This problem happens because of how tracklists are cached on the bot. My bet is that "Lifeblood" was released as a single on Spotify (Main source of tracklists). So the first time that someone asked the bot for the tracklist of "Lifeblood", only the single existed and the full album did not exist yet, so that got cached on the bot.

I deleted the cached version and now it should render the full album properly. 

I will try to improve the tracklist handling in the future, including allowing multiple tracklist for one album, selecting one as a default and customization, but it will take a while to get this functionallity going. 😔

**Comment by daves003** [comment]
Ah I see. Lifeblood did indeed get released as a single first before the album came out.
It renders correctly now thank you :D
Maybe adding a `--refresh` flag to commands to clear and reload the cache would be a decent option that wouldn't require a lot of development?
