### ISSUE TITLE
Run-D.M.C. not being read

### ISSUE THREAD

**Issue by Hotspotmar** [ishwi/Chuu#48]
Today we tried to use `!wk RunDMC` it would always return `No one knows Run-D.M.C.` 
But when playing a Rundmc song in spotify and using !wk it would return the expected results.

**Comment by ishwi** [comment]
Hi, thanks for submitting the issue and  sorry I didn't see the issue earlier, missed it completely... 

First of all this issue happens due to last.fm redirections. When you do `!wk` and it obtains the artist from your now playing artist it will use [an artist name with a long dash](https://www.last.fm/music/Run%E2%80%93D.M.C.): –

When you do `!wk RunDMC ` it goes through the redirection system of last.fm and ends up choosing  [an artist name with a short dash](https://www.last.fm/music/Run-D.M.C.): -

You can see the two artist on the bot database in the following screenshot.
![image](https://user-images.githubusercontent.com/24591814/117540880-8c514100-b011-11eb-9ec5-328c747c3578.png)
First one being the long dash and second one being the short dash. 

Since the long dash version has 5 times the listeners i have decided to make the redirection of `RunDMC` go to the long dash version. 

So now it should work as expected for you. (For some other people that have their scrobbles on the short dash one it will not be a good change i guess :D)
