### ISSUE TITLE
Respondes late / wrong artist

### ISSUE THREAD

**Issue by alexadev10** [ishwi/Chuu#49]
After a command is given to the bot it has a strang delay of like 10 seconds and then it respondes but this delay it comes random.
Another problem is that the bot tells me that i am listeming to a diffrtent then the one i am actually listening to.

**Comment by ishwi** [comment]
The delays usually happen when the database server is under stress.  Which is happening right now, and probably when you submitted this issue. 
Also the problem with your now playing artist is not really related to the bot itself. 
The bot only displays what your last.fm account shows. So in this case, your last.fm account is not being properly updated.
This is a common thing with last.fm, even more so if you are an spotify user.

We have this written in our faq in the [support server](https://discord.gg/HQGqYD7):

> Q: Chuu is showing the wrong track that I'm currently playing/ doesn't show what I'm playing / my Last.fm stopped scrobbling:
> A: This is mainly a Last.fm issue and will resolve itself within a few minutes/hours.
> If the problem still persists (and if you're using the spotify connection), please disconnect and then reconnect your spotify account with your last.fm from: Last.fm account -> Settings -> Applications
> You can also check this out for additional help: https://support.last.fm/t/spotify-has-stopped-scrobbling-what-can-i-do/3184


I will close this issue as the slowdowns are something temporal (but sadly frequent) due to slow hardware and/or heavy load, and the second issue not being a problem with the bot.
