### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by hoeliday** [ishwi/Chuu#68]
so currently this has been happening to many people including myself. whenever, people do !wk or !wkt they appear on the board when they do it but when someone else does it they don’t appear or I don’t. last.fm account was set and sometimes when I go and use a command it’s not set?

**Comment by yayuyokitano** [comment]
The most common explanation for !gwk not working is that you have been marked as having botted or otherwise inflated scrobbles (imported scrobbles are allowed). If you believe your scrobble count is not botted or otherwise inflated, you should join the [Chuu support server](https://discord.gg/3tYsPMWvQG)  and ask in assistance channel so mods can inspect and confirm if it is a bug or not. You can see !gwk leaderboard including accounts marked as botted by adding the --botted flag when calling it.

As for !wk, the issue should be solved if you do the !serverset command in the server in question. If this does not solve the issue I once again recommend joining the chuu support server and asking in assistance so more steps can be tried.

**Comment by hoeliday** [comment]
I think I’ve found the issue thank you though
